-- game.ReplicatedStorage.Database.Audio.Bullet

local v1 = {}
local v2 = {
	["Identifiers"] = { 111838400230650 },
	["Properties"] = {
		["RollOffMaxDistance"] = 115,
		["RollOffMinDistance"] = 5,
		["Volume"] = 0.65
	}
}
v1["Helmet Headshot"] = v2
local v3 = {
	["Identifiers"] = {
		116639648417232,
		95414497824727,
		78608644557374,
		119993641013496,
		134327056918840,
		110899533478540
	},
	["Properties"] = {
		["Volume"] = 0.75
	}
}
v1.Whizz = v3
local v4 = {
	["Identifiers"] = { 97158277270389 },
	["Properties"] = {
		["RollOffMaxDistance"] = 115,
		["RollOffMinDistance"] = 5,
		["Volume"] = 0.65
	}
}
v1.Headshot = v4
local v5 = {
	["Identifiers"] = {
		107667789878316,
		124912612009209,
		92566163061648,
		117996590042443
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 115,
		["RollOffMinDistance"] = 15,
		["Volume"] = 1
	}
}
v1["Blood Splatter"] = v5
local v6 = {
	["Identifiers"] = { 111405553756660 },
	["Properties"] = {
		["RollOffMaxDistance"] = 115,
		["RollOffMinDistance"] = 15,
		["Volume"] = 1.2
	}
}
v1["Glass Shattered"] = v6
local v7 = {
	["Identifiers"] = { 107552816288023 },
	["Properties"] = {
		["RollOffMaxDistance"] = 60,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.35
	}
}
v1["Break Flower Pot"] = v7
local v8 = {
	["Identifiers"] = { 98382879264498 },
	["Properties"] = {
		["RollOffMaxDistance"] = 60,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.35
	}
}
v1["Break Metal Vent"] = v8
local v9 = {
	["Identifiers"] = { 90197289900257 },
	["Properties"] = {
		["RollOffMaxDistance"] = 60,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.35
	}
}
v1["Break Market Window"] = v9
local v10 = {
	["Identifiers"] = { 79282272210643, 119963893130403, 97511586360655 },
	["Properties"] = {
		["RollOffMaxDistance"] = 35,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.5
	}
}
v1.Basalt = v10
local v11 = {
	["Identifiers"] = { 109459843208617, 122760233936415, 130557426886688 },
	["Properties"] = {
		["RollOffMaxDistance"] = 35,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.5
	}
}
v1.Sand = v11
local v12 = {
	["Identifiers"] = {
		80786157006736,
		90972520785791,
		79758931061610,
		115766484991072,
		97986986618474,
		101518218189509
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 35,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.5
	}
}
v1.Metal = v12
local v13 = {
	["Identifiers"] = { 17703240689 },
	["Properties"] = {
		["RollOffMaxDistance"] = 35,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.5
	}
}
v1.Concrete = v13
local v14 = {
	["Identifiers"] = { 17703246768 },
	["Properties"] = {
		["RollOffMaxDistance"] = 35,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.5
	}
}
v1.Fabric = v14
local v15 = {
	["Identifiers"] = { 17703242867 },
	["Properties"] = {
		["RollOffMaxDistance"] = 35,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.5
	}
}
v1.Glass = v15
local v16 = {
	["Identifiers"] = { 17703246768 },
	["Properties"] = {
		["RollOffMaxDistance"] = 35,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.5
	}
}
v1.Ground = v16
local v17 = {
	["Identifiers"] = { 17703248112 },
	["Properties"] = {
		["RollOffMaxDistance"] = 35,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.5
	}
}
v1.Wood = v17
local v18 = {
	["Identifiers"] = { 88431967085529, 110236224862357, 113973450260838 },
	["Properties"] = {
		["RollOffMaxDistance"] = 35,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.5
	}
}
v1.WoodPlanks = v18
local v19 = {
	["Identifiers"] = { 72604279396039, 120526288777769, 103333179421673 },
	["Properties"] = {
		["RollOffMaxDistance"] = 35,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.5
	}
}
v1.CeramicTiles = v19
local v20 = {
	["Identifiers"] = {
		83421856921864,
		77544488525688,
		92763417682099,
		79925686421929
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 35,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.5
	}
}
v1.Cardboard = v20
local v21 = {
	["Identifiers"] = { 119517587281145, 77483025143735 },
	["Properties"] = {
		["RollOffMaxDistance"] = 35,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.5
	}
}
v1.CorrodedMetal = v21
local v22 = {
	["Identifiers"] = { 76556926351022, 131099898339393 },
	["Properties"] = {
		["RollOffMaxDistance"] = 35,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.5
	}
}
v1.Pebble = v22
return table.freeze(v1)