-- game.ReplicatedStorage.Database.Audio.Counter-Terrorists

local v1 = {}
local v2 = {
	["Identifiers"] = { 108153572925965 },
	["Properties"] = {
		["Volume"] = 1
	}
}
v1["Hostage Rescue In Progress"] = v2
local v3 = {
	["Identifiers"] = { 130208466949276 },
	["Properties"] = {
		["Volume"] = 1
	}
}
v1["Hostage Dropped"] = v3
local v4 = {
	["Identifiers"] = { 112475648284823 },
	["Properties"] = {
		["Volume"] = 1
	}
}
v1["Hostage Rescued"] = v4
local v5 = {
	["Identifiers"] = { 81928823991723 },
	["Properties"] = {
		["Volume"] = 1.3
	}
}
v1["Bomb Planted"] = v5
local v6 = {
	["Identifiers"] = { 98209382296621 },
	["Properties"] = {
		["RollOffMaxDistance"] = 0,
		["RollOffMinDistance"] = 0,
		["Volume"] = 0.333,
		["Looped"] = false
	}
}
v1["Bomb Planted Music"] = v6
local v7 = {
	["Identifiers"] = { 97606210523181 },
	["Properties"] = {
		["Volume"] = 1.3
	}
}
v1["Bomb Defused"] = v7
local v8 = {
	["Identifiers"] = { 135379143040468, 84285453336239 },
	["Properties"] = {
		["RollOffMaxDistance"] = 120,
		["RollOffMinDistance"] = 25,
		["Volume"] = 1
	}
}
v1["Throwing Smoke Grenade"] = v8
local v9 = {
	["Identifiers"] = { 91021017124685, 104534030742266 },
	["Properties"] = {
		["RollOffMaxDistance"] = 120,
		["RollOffMinDistance"] = 25,
		["Volume"] = 1
	}
}
v1["Throwing Flashbang"] = v9
local v10 = {
	["Identifiers"] = { 115884192706975, 126592229993563 },
	["Properties"] = {
		["RollOffMaxDistance"] = 120,
		["RollOffMinDistance"] = 25,
		["Volume"] = 1
	}
}
v1["Throwing HE Grenade"] = v10
local v11 = {
	["Identifiers"] = { 118084208137962 },
	["Properties"] = {
		["RollOffMaxDistance"] = 120,
		["RollOffMinDistance"] = 25,
		["Volume"] = 1
	}
}
v1["Throwing Incendiary Grenade"] = v11
local v12 = {
	["Identifiers"] = { 83666590558608 },
	["Properties"] = {
		["RollOffMaxDistance"] = 120,
		["RollOffMinDistance"] = 25,
		["Volume"] = 1
	}
}
v1["Throwing Molotov"] = v12
local v13 = {
	["Identifiers"] = { 97340126821311, 88715148224021 },
	["Properties"] = {
		["RollOffMaxDistance"] = 120,
		["RollOffMinDistance"] = 25,
		["Volume"] = 1
	}
}
v1["Throwing Decoy Grenade"] = v13
local v14 = {
	["Identifiers"] = { 94141667493613, 75636280774479, 73096326509225 },
	["Properties"] = {
		["RollOffMaxDistance"] = 120,
		["RollOffMinDistance"] = 25,
		["Volume"] = 1.1
	}
}
v1.Death = v14
return table.freeze(v1)