-- game.ReplicatedStorage.Database.Audio.FloorSounds

local v1 = {}
local v2 = {
	["Identifiers"] = { 137688704744382 },
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.Jump = v2
local v3 = {
	["Identifiers"] = { 137942600526896, 87522147963786 },
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.LandingConcrete = v3
local v4 = {
	["Identifiers"] = { 88884325314428 },
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.LandingDirt = v4
local v5 = {
	["Identifiers"] = { 111300901511229 },
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.LandingGlass = v5
local v6 = {
	["Identifiers"] = { 137293032987455 },
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.LandingGravel = v6
local v7 = {
	["Identifiers"] = { 108750974913697 },
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.LandingRubber = v7
local v8 = {
	["Identifiers"] = { 128616595967424 },
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.LandingSand = v8
local v9 = {
	["Identifiers"] = { 88593562868218 },
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.LandingGrass = v9
local v10 = {
	["Identifiers"] = { 132231082392229 },
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.LandingMetal = v10
local v11 = {
	["Identifiers"] = {
		74561606433669,
		70754132591874,
		95016086746392,
		97857151436349,
		104795114912100
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1. = v11
local v12 = {
	["Identifiers"] = {
		90972520785791,
		79758931061610,
		115766484991072,
		97986986618474,
		101518218189509
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1["Corroded Metal"] = v12
local v13 = {
	["Identifiers"] = {
		89959893851166,
		97403386167602,
		93839110027266,
		120626314763668,
		99411881656973
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.CeramicTiles = v13
local v14 = {
	["Identifiers"] = {
		112474714827172,
		103499149720651,
		91808449371840,
		120343016099550,
		132309503551091
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.Wood = v14
local v15 = {
	["Identifiers"] = {
		112474714827172,
		103499149720651,
		91808449371840,
		120343016099550,
		132309503551091
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.WoodPlanks = v15
local v16 = {
	["Identifiers"] = {
		83674947450074,
		113456996486974,
		132999946433162,
		78755569275831,
		106583906112036
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.Sand = v16
local v17 = {
	["Identifiers"] = {
		119676680755592,
		71176804308705,
		116894872455910,
		135055866096660,
		137980195168871
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.Metal = v17
local v18 = {
	["Identifiers"] = {
		127886531439205,
		78434499521137,
		87897229152313,
		133514494864081,
		101332457814754
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.Grass = v18
local v19 = {
	["Identifiers"] = {
		124220575764299,
		99619709352369,
		91112566680393,
		81336760971812,
		100151504500732
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.Ground = v19
local v20 = {
	["Identifiers"] = {
		124220575764299,
		99619709352369,
		91112566680393,
		81336760971812,
		100151504500732
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.Plastic = v20
local v21 = {
	["Identifiers"] = {
		124220575764299,
		99619709352369,
		91112566680393,
		81336760971812,
		100151504500732
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.Cardboard = v21
local v22 = {
	["Identifiers"] = {
		95929468123910,
		103926370274345,
		84663738469550,
		98924895677582,
		123314510077949
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.Concrete = v22
local v23 = {
	["Identifiers"] = {
		95929468123910,
		103926370274345,
		84663738469550,
		98924895677582,
		123314510077949
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.Pebble = v23
local v24 = {
	["Identifiers"] = { 97513129935391, 78067281367528 },
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.DiamondPlate = v24
local v25 = {
	["Identifiers"] = {
		129507063035282,
		139699015668288,
		79163864375780,
		130063108622384,
		72458634886260
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.Carpet = v25
local v26 = {
	["Identifiers"] = {
		129507063035282,
		139699015668288,
		79163864375780,
		130063108622384,
		72458634886260
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.Fabric = v26
local v27 = {
	["Identifiers"] = {
		116193421799867,
		126868880835903,
		131229119808848,
		96139138946771
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.Snow = v27
local v28 = {
	["Identifiers"] = {
		116193421799867,
		126868880835903,
		131229119808848,
		96139138946771
	},
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.Mud = v28
local v29 = {
	["Identifiers"] = { 79654188653339, 86778232120558, 76162060331543 },
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["TimePosition"] = 0,
		["Looped"] = false,
		["Volume"] = 0.675
	}
}
v1.Asphalt = v29
return table.freeze(v1)