-- game.ReplicatedStorage.Database.Audio.Grenade

local v1 = {}
local v2 = {
	["Identifiers"] = { 88305429005809 },
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.Bounce = v2
local v3 = {
	["Identifiers"] = { 116675737467831 },
	["Properties"] = {
		["RollOffMaxDistance"] = 115,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1,
		["Looped"] = true
	}
}
v1.Flames = v3
return table.freeze(v1)