-- game.ReplicatedStorage.Database.Audio.Interface

local v1 = {}
local v2 = {
	["Identifiers"] = { 118853597176073 },
	["Properties"] = {
		["Volume"] = 0.5
	}
}
v1["Countdown Timer"] = v2
local v3 = {
	["Identifiers"] = { 82124512714941, 75981401603584 },
	["Properties"] = {
		["Volume"] = 0.5
	}
}
v1["UI Settings Click"] = v3
local v4 = {
	["Identifiers"] = { 89468671221334, 115771889681402 },
	["Properties"] = {
		["Volume"] = 0.5
	}
}
v1["UI Inventory Click"] = v4
local v5 = {
	["Identifiers"] = { 121370835394811, 88975334727935 },
	["Properties"] = {
		["Volume"] = 0.5
	}
}
v1["UI Play Click"] = v5
local v6 = {
	["Identifiers"] = { 122541995194558 },
	["Properties"] = {
		["Volume"] = 0.5
	}
}
v1["UI Dashboard Click"] = v6
local v7 = {
	["Identifiers"] = { 137394104365918 },
	["Properties"] = {
		["Volume"] = 0.5
	}
}
v1["UI Loadout Click"] = v7
local v8 = {
	["Identifiers"] = { 137394104365918 },
	["Properties"] = {
		["Volume"] = 0.5
	}
}
v1["UI Store Click"] = v8
local v9 = {
	["Identifiers"] = { 137394104365918 },
	["Properties"] = {
		["Volume"] = 0.5
	}
}
v1["UI Modes Click"] = v9
local v10 = {
	["Identifiers"] = { 99663955686471, 118361641765535, 85560049554585 },
	["Properties"] = {
		["Volume"] = 0.5
	}
}
v1["UI Highlight"] = v10
local v11 = {
	["Identifiers"] = { 137394104365918 },
	["Properties"] = {
		["Volume"] = 0.5
	}
}
v1["UI Click"] = v11
local v12 = {
	["Identifiers"] = { 138767051272856 },
	["Properties"] = {
		["Volume"] = 0.5
	}
}
v1["Successful Buy Menu Purchase"] = v12
local v13 = {
	["Identifiers"] = { 84091803404257 },
	["Properties"] = {
		["Volume"] = 0.5
	}
}
v1["Notification Error"] = v13
local v14 = {
	["Identifiers"] = { 98360775959854 },
	["Properties"] = {
		["Volume"] = 0.5
	}
}
v1["Notification Success"] = v14
local v15 = {
	["Identifiers"] = { 102233699262397 },
	["Properties"] = {
		["Volume"] = 0.75
	}
}
v1["XP Bar Fill"] = v15
local v16 = {
	["Identifiers"] = { 128387923593423 },
	["Properties"] = {
		["Volume"] = 0.75
	}
}
v1["Level Up"] = v16
return table.freeze(v1)