-- game.ReplicatedStorage.Database.Audio.Miscellaneous

local v1 = {}
local v2 = {
	["Identifiers"] = { 131273847577128 },
	["Properties"] = {
		["RollOffMaxDistance"] = 60,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1["Open Garage"] = v2
local v3 = {
	["Identifiers"] = { 139971250122237 },
	["Properties"] = {
		["RollOffMaxDistance"] = 60,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1["Close Garage"] = v3
return table.freeze(v1)