-- game.ReplicatedStorage.Database.Audio.Store

local v1 = {}
local v2 = {
	["Identifiers"] = { 105681920256526 },
	["Properties"] = {
		["Volume"] = 1
	}
}
v1["Successful Purchase"] = v2
local v3 = {
	["Identifiers"] = { 76537644589472 },
	["Properties"] = {
		["Volume"] = 1
	}
}
v1["Case Opening"] = v3
local v4 = {
	["Identifiers"] = { 73905462058647 },
	["Properties"] = {
		["Volume"] = 1
	}
}
v1["Case Close"] = v4
local v5 = {
	["Identifiers"] = { 134947659964816 },
	["Properties"] = {
		["Volume"] = 1
	}
}
v1["Case Roll Tick"] = v5
local v6 = {
	["Identifiers"] = { 109653502187519 },
	["Properties"] = {
		["Volume"] = 1
	}
}
v1["Case Fall"] = v6
local v7 = {
	["Identifiers"] = { 118053561399536 },
	["Properties"] = {
		["Volume"] = 2
	}
}
v1["Charm Drag Start"] = v7
local v8 = {
	["Identifiers"] = { 122392709028764 },
	["Properties"] = {
		["Volume"] = 2,
		["Looped"] = false
	}
}
v1["Charm Drag Loop"] = v8
local v9 = {
	["Identifiers"] = { 81801736236778 },
	["Properties"] = {
		["Volume"] = 2
	}
}
v1["Package Drop"] = v9
local v10 = {
	["Identifiers"] = { 96074431590029 },
	["Properties"] = {
		["Volume"] = 2
	}
}
v1["Package Right Tape"] = v10
local v11 = {
	["Identifiers"] = { 71576549453097 },
	["Properties"] = {
		["Volume"] = 2
	}
}
v1["Package Left Tape"] = v11
local v12 = {
	["Identifiers"] = { 139940823424719 },
	["Properties"] = {
		["Volume"] = 2
	}
}
v1["Package Front Lid"] = v12
local v13 = {
	["Identifiers"] = { 87092023166122 },
	["Properties"] = {
		["Volume"] = 2
	}
}
v1["Package Final Open"] = v13
return table.freeze(v1)