-- game.ReplicatedStorage.Database.Audio.Terrorists

local v1 = {}
local v2 = {
	["Identifiers"] = { 115140779482842, 88634080120233 },
	["Properties"] = {
		["RollOffMaxDistance"] = 120,
		["RollOffMinDistance"] = 25,
		["Volume"] = 1.25
	}
}
v1["Planting bomb"] = v2
local v3 = {
	["Identifiers"] = { 135058881646144, 86027329305419 },
	["Properties"] = {
		["RollOffMaxDistance"] = 120,
		["RollOffMinDistance"] = 25,
		["Volume"] = 1
	}
}
v1["Throwing Smoke Grenade"] = v3
local v4 = {
	["Identifiers"] = { 100233273666271, 98456275706455 },
	["Properties"] = {
		["RollOffMaxDistance"] = 120,
		["RollOffMinDistance"] = 25,
		["Volume"] = 1
	}
}
v1["Throwing Flashbang"] = v4
local v5 = {
	["Identifiers"] = { 111954056952523, 128099708243009 },
	["Properties"] = {
		["RollOffMaxDistance"] = 120,
		["RollOffMinDistance"] = 25,
		["Volume"] = 1
	}
}
v1["Throwing HE Grenade"] = v5
local v6 = {
	["Identifiers"] = { 95908032396502 },
	["Properties"] = {
		["RollOffMaxDistance"] = 120,
		["RollOffMinDistance"] = 25,
		["Volume"] = 1
	}
}
v1["Throwing Incendiary Grenade"] = v6
local v7 = {
	["Identifiers"] = { 84829160150572 },
	["Properties"] = {
		["RollOffMaxDistance"] = 120,
		["RollOffMinDistance"] = 25,
		["Volume"] = 1
	}
}
v1["Throwing Molotov"] = v7
local v8 = {
	["Identifiers"] = { 120361810997490, 71431959853004 },
	["Properties"] = {
		["RollOffMaxDistance"] = 120,
		["RollOffMinDistance"] = 25,
		["Volume"] = 1
	}
}
v1["Throwing Decoy Grenade"] = v8
local v9 = {
	["Identifiers"] = { 94141667493613, 75636280774479, 73096326509225 },
	["Properties"] = {
		["RollOffMaxDistance"] = 120,
		["RollOffMinDistance"] = 25,
		["Volume"] = 1.1
	}
}
v1.Death = v9
return table.freeze(v1)