-- game.ReplicatedStorage.Components.Common.CreateRagdoll.Common.MaxFrictionTorque

return table.freeze({
	["Head"] = 400,
	["UpperTorso"] = 500,
	["LowerTorso"] = 500,
	["LeftUpperArm"] = 300,
	["LeftLowerArm"] = 200,
	["LeftHand"] = 100,
	["RightUpperArm"] = 300,
	["RightLowerArm"] = 200,
	["RightHand"] = 100,
	["LeftUpperLeg"] = 400,
	["LeftLowerLeg"] = 300,
	["LeftFoot"] = 150,
	["RightUpperLeg"] = 400,
	["RightLowerLeg"] = 300,
	["RightFoot"] = 150
})