-- game.ReplicatedStorage.Database.Custom.GameStats.Settings.Colors

local v1 = {}
v1["Bright White"] = table.freeze({
	["Counter-Terrorists"] = Color3.fromRGB(235, 235, 235),
	["Terrorists"] = Color3.fromRGB(235, 235, 235)
})
v1["Light Blue"] = table.freeze({
	["Counter-Terrorists"] = Color3.fromRGB(153, 204, 255),
	["Terrorists"] = Color3.fromRGB(153, 204, 255)
})
v1.Purple = table.freeze({
	["Counter-Terrorists"] = Color3.fromRGB(153, 51, 204),
	["Terrorists"] = Color3.fromRGB(153, 51, 204)
})
v1.Yellow = table.freeze({
	["Counter-Terrorists"] = Color3.fromRGB(255, 221, 51),
	["Terrorists"] = Color3.fromRGB(255, 221, 51)
})
v1.White = table.freeze({
	["Counter-Terrorists"] = Color3.fromRGB(255, 255, 255),
	["Terrorists"] = Color3.fromRGB(255, 255, 255)
})
v1.Pink = table.freeze({
	["Counter-Terrorists"] = Color3.fromRGB(255, 102, 178),
	["Terrorists"] = Color3.fromRGB(255, 102, 178)
})
v1.Orange = table.freeze({
	["Counter-Terrorists"] = Color3.fromRGB(255, 128, 0),
	["Terrorists"] = Color3.fromRGB(255, 128, 0)
})
v1.Aqua = table.freeze({
	["Counter-Terrorists"] = Color3.fromRGB(0, 204, 204),
	["Terrorists"] = Color3.fromRGB(0, 204, 204)
})
v1.Blue = table.freeze({
	["Counter-Terrorists"] = Color3.fromRGB(0, 102, 204),
	["Terrorists"] = Color3.fromRGB(0, 102, 204)
})
v1.Green = table.freeze({
	["Counter-Terrorists"] = Color3.fromRGB(0, 153, 0),
	["Terrorists"] = Color3.fromRGB(0, 153, 0)
})
v1.Red = table.freeze({
	["Counter-Terrorists"] = Color3.fromRGB(204, 0, 0),
	["Terrorists"] = Color3.fromRGB(204, 0, 0)
})
v1["Team Color"] = table.freeze({
	["Counter-Terrorists"] = Color3.fromRGB(165, 183, 212),
	["Terrorists"] = Color3.fromRGB(219, 199, 126)
})
return table.freeze(v1)