-- game.ReplicatedStorage.Controllers.InputController.Actions.Inspect

local v_replicatedstorage = game:GetService("ReplicatedStorage")
local v_players = game:GetService("Players")
require(script.Parent.Parent.Types)
local v_u_localplayer = v_players.LocalPlayer
local v_u1 = require(v_replicatedstorage.Controllers.InventoryController)
local v_u2 = require(v_replicatedstorage.Controllers.HintController)
return table.freeze({
	["Name"] = "Inspect",
	["Group"] = "Gameplay",
	["Category"] = "Weapon Keys",
	["Callback"] = function(arg1, _)
		-- upvalues: (copy) v_u_localplayer, (copy) v_u1, (copy) v_u2
		if v_u_localplayer:GetAttribute("IsPlayerChatting") then
			return
		elseif arg1 == Enum.UserInputState.Begin then
			local v_getcurrentequipped = v_u1.getCurrentEquipped()
			if v_getcurrentequipped then
				v_getcurrentequipped:inspect()
				v_u2:clearHint("Inspect")
			end
		else
			return
		end
	end
})