-- game.ReplicatedStorage.Database.Custom.GameStats.InventorySchemas.Bomb Defusal

local v1 = {
	["MaxInventorySpace"] = 5
}
local v2 = {
	{
		["MaxSlotSpace"] = 1,
		["Type"] = "Primary"
	},
	{
		["MaxSlotSpace"] = 1,
		["Type"] = "Secondary"
	},
	{
		["MaxSlotSpace"] = 1,
		["Type"] = "Melee"
	},
	{
		["MaxSlotSpace"] = 4,
		["Type"] = "Grenade"
	},
	{
		["MaxSlotSpace"] = 1,
		["Type"] = "C4"
	}
}
v1.InventorySlots = v2
return table.freeze(v1)