-- game.ReplicatedStorage.Database.Audio.Weapons.AWP

local v1 = {}
local v2 = {
	["Identifiers"] = { 103474672461684 },
	["Properties"] = {
		["RollOffMaxDistance"] = 300,
		["RollOffMinDistance"] = 40,
		["Volume"] = 0.95
	}
}
v1.Shoot = v2
local v3 = {
	["Identifiers"] = { 87995834264461 },
	["Properties"] = {
		["RollOffMaxDistance"] = 130,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.Draw = v3
local v4 = {
	["Identifiers"] = { 105389451134219 },
	["Properties"] = {
		["RollOffMaxDistance"] = 130,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.MagOut = v4
local v5 = {
	["Identifiers"] = { 130036942909324 },
	["Properties"] = {
		["RollOffMaxDistance"] = 130,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.MagIn = v5
local v6 = {
	["Identifiers"] = { 79126805687724 },
	["Properties"] = {
		["RollOffMaxDistance"] = 130,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.MagIn2 = v6
local v7 = {
	["Identifiers"] = { 90501801326987 },
	["Properties"] = {
		["RollOffMaxDistance"] = 130,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.BoltBack = v7
local v8 = {
	["Identifiers"] = { 75302689916854 },
	["Properties"] = {
		["RollOffMaxDistance"] = 130,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.BoltForward = v8
local v9 = {
	["Identifiers"] = { 75760061373660 },
	["Properties"] = {
		["RollOffMaxDistance"] = 130,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.Zoom = v9
return table.freeze(v1)