-- game.ReplicatedStorage.Database.Audio.Weapons.C4

local v1 = {}
local v2 = {
	["Identifiers"] = { 101443735939622, 124701328596831 },
	["Properties"] = {
		["RollOffMaxDistance"] = 105,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1["7"] = v2
local v3 = {
	["Identifiers"] = { 101443735939622, 124701328596831 },
	["Properties"] = {
		["RollOffMaxDistance"] = 105,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1["73"] = v3
local v4 = {
	["Identifiers"] = { 101443735939622, 124701328596831 },
	["Properties"] = {
		["RollOffMaxDistance"] = 105,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1["735"] = v4
local v5 = {
	["Identifiers"] = { 101443735939622, 124701328596831 },
	["Properties"] = {
		["RollOffMaxDistance"] = 105,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1["7355"] = v5
local v6 = {
	["Identifiers"] = { 101443735939622, 124701328596831 },
	["Properties"] = {
		["RollOffMaxDistance"] = 105,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1["73556"] = v6
local v7 = {
	["Identifiers"] = { 101443735939622, 124701328596831 },
	["Properties"] = {
		["RollOffMaxDistance"] = 105,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1["735560"] = v7
local v8 = {
	["Identifiers"] = { 101443735939622, 124701328596831 },
	["Properties"] = {
		["RollOffMaxDistance"] = 105,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1["7355608"] = v8
local v9 = {
	["Identifiers"] = { 110821133065020 },
	["Properties"] = {
		["RollOffMaxDistance"] = 90,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.Equip = v9
local v10 = {
	["Identifiers"] = { 127838797417740 },
	["Properties"] = {
		["RollOffMaxDistance"] = 105,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.Planting = v10
local v11 = {
	["Identifiers"] = { 89812975881685 },
	["Properties"] = {
		["RollOffMaxDistance"] = 105,
		["RollOffMinDistance"] = 10,
		["Volume"] = 2
	}
}
v1.Beep = v11
local v12 = {
	["Identifiers"] = { 122031800060058 },
	["Properties"] = {
		["RollOffMaxDistance"] = 105,
		["RollOffMinDistance"] = 20,
		["Volume"] = 1
	}
}
v1.Explosion = v12
local v13 = {
	["Identifiers"] = { 110360556399810 },
	["Properties"] = {
		["RollOffMaxDistance"] = 105,
		["RollOffMinDistance"] = 12,
		["Volume"] = 1
	}
}
v1.Defusing = v13
return table.freeze(v1)