-- game.ReplicatedStorage.Database.Audio.Weapons.Flip Knife

local v1 = {}
local v2 = {
	["Identifiers"] = { 129882566822814 },
	["Properties"] = {
		["RollOffMaxDistance"] = 50,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.9
	}
}
v1.Equip = v2
local v3 = {
	["Identifiers"] = { 89185508106386 },
	["Properties"] = {
		["RollOffMaxDistance"] = 50,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.HitOne = v3
local v4 = {
	["Identifiers"] = { 89185508106386 },
	["Properties"] = {
		["RollOffMaxDistance"] = 50,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.HitTwo = v4
local v5 = {
	["Identifiers"] = { 89185508106386 },
	["Properties"] = {
		["RollOffMaxDistance"] = 50,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.HitThree = v5
local v6 = {
	["Identifiers"] = { 125726459155685 },
	["Properties"] = {
		["RollOffMaxDistance"] = 50,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.BackStab = v6
local v7 = {
	["Identifiers"] = { 84292728084061 },
	["Properties"] = {
		["RollOffMaxDistance"] = 50,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.9
	}
}
v1.Handling1 = v7
local v8 = {
	["Identifiers"] = { 131742455196849 },
	["Properties"] = {
		["RollOffMaxDistance"] = 50,
		["RollOffMinDistance"] = 10,
		["Volume"] = 0.9
	}
}
v1.Handling2 = v8
return table.freeze(v1)