-- game.ReplicatedStorage.Database.Audio.Weapons.M4A1-S

local v1 = {}
local v2 = {
	["Identifiers"] = { 80702375430296 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.MagOut = v2
local v3 = {
	["Identifiers"] = { 77653564064830 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.MagIn = v3
local v4 = {
	["Identifiers"] = { 110129262300933 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.Tap = v4
local v5 = {
	["Identifiers"] = { 112825283651370 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.BoltPull = v5
local v6 = {
	["Identifiers"] = { 80470576683196 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.BoltRelease = v6
local v7 = {
	["Identifiers"] = { 87995834264461 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.Equip = v7
local v8 = {
	["Identifiers"] = { 135939436101358 },
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 25,
		["Volume"] = 0.85
	}
}
v1.Shoot = v8
local v9 = {
	["Identifiers"] = { 90698793665750, 86582201819894, 91665393784211 },
	["Properties"] = {
		["RollOffMaxDistance"] = 300,
		["RollOffMinDistance"] = 40,
		["Volume"] = 0.85
	}
}
v1.Silencer = v9
local v10 = {
	["Identifiers"] = { 137420606854537 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.ScrewStart = v10
local v11 = {
	["Identifiers"] = { 127244678889692 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.ScrewOn1 = v11
local v12 = {
	["Identifiers"] = { 81692430991273 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.ScrewOn2 = v12
local v13 = {
	["Identifiers"] = { 121216229724655 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.ScrewOn3 = v13
local v14 = {
	["Identifiers"] = { 97800142763870 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.ScrewOn4 = v14
local v15 = {
	["Identifiers"] = { 91208073355604 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.ScrewOn5 = v15
local v16 = {
	["Identifiers"] = { 110387218269014 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.ScrewOnEnd = v16
return table.freeze(v1)