-- game.ReplicatedStorage.Database.Audio.Weapons.M9 Bayonet

local v1 = {}
local v2 = {
	["Identifiers"] = { 91729110777679 },
	["Properties"] = {
		["RollOffMaxDistance"] = 50,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.Equip = v2
local v3 = {
	["Identifiers"] = { 89185508106386 },
	["Properties"] = {
		["RollOffMaxDistance"] = 50,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.HitOne = v3
local v4 = {
	["Identifiers"] = { 89185508106386 },
	["Properties"] = {
		["RollOffMaxDistance"] = 50,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.HitTwo = v4
local v5 = {
	["Identifiers"] = { 89185508106386 },
	["Properties"] = {
		["RollOffMaxDistance"] = 50,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.HitThree = v5
local v6 = {
	["Identifiers"] = { 125726459155685 },
	["Properties"] = {
		["RollOffMaxDistance"] = 50,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.BackStab = v6
return table.freeze(v1)