-- game.ReplicatedStorage.Database.Audio.Weapons.Other

local v1 = {}
local v2 = {
	["Identifiers"] = { 84239484255879 },
	["Properties"] = {
		["RollOffMaxDistance"] = 90,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1["Switch Fire Mode"] = v2
local v3 = {
	["Identifiers"] = { 124772612909241 },
	["Properties"] = {
		["RollOffMaxDistance"] = 90,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1["Scope In"] = v3
local v4 = {
	["Identifiers"] = { 80232125926926 },
	["Properties"] = {
		["RollOffMaxDistance"] = 90,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1["Scope Out"] = v4
local v5 = {
	["Identifiers"] = { 127466955748548 },
	["Properties"] = {
		["RollOffMaxDistance"] = 90,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1["Toggle Scope"] = v5
local v6 = {
	["Identifiers"] = { 114504997850933 },
	["Properties"] = {
		["RollOffMaxDistance"] = 90,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1["No Ammo"] = v6
return table.freeze(v1)