-- game.ReplicatedStorage.Database.Audio.Weapons.USP-S

local v1 = {}
local v2 = {
	["Identifiers"] = { 128601301376982 },
	["Properties"] = {
		["RollOffMaxDistance"] = 300,
		["RollOffMinDistance"] = 35,
		["Volume"] = 0.85
	}
}
v1.Silencer = v2
local v3 = {
	["Identifiers"] = { 137420606854537 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.ScrewStart = v3
local v4 = {
	["Identifiers"] = { 127244678889692 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.ScrewOn1 = v4
local v5 = {
	["Identifiers"] = { 81692430991273 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.ScrewOn2 = v5
local v6 = {
	["Identifiers"] = { 121216229724655 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.ScrewOn3 = v6
local v7 = {
	["Identifiers"] = { 97800142763870 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.ScrewOn4 = v7
local v8 = {
	["Identifiers"] = { 91208073355604 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.ScrewOn5 = v8
local v9 = {
	["Identifiers"] = { 110387218269014 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.ScrewOnEnd = v9
local v10 = {
	["Identifiers"] = { 4108910200 },
	["Properties"] = {
		["RollOffMaxDistance"] = 85,
		["RollOffMinDistance"] = 25,
		["Volume"] = 1.7
	}
}
v1.Shoot = v10
local v11 = {
	["Identifiers"] = { 136519660614746 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 2
	}
}
v1.MagIn = v11
local v12 = {
	["Identifiers"] = { 70997008656860 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 2
	}
}
v1.MagOut = v12
local v13 = {
	["Identifiers"] = { 132765693291490 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.Bolt = v13
local v14 = {
	["Identifiers"] = { 117148840921052 },
	["Properties"] = {
		["RollOffMaxDistance"] = 100,
		["RollOffMinDistance"] = 10,
		["Volume"] = 1
	}
}
v1.Handling = v14
return table.freeze(v1)